sax_a_leistungsgrenzwert_entladen:
  name: Leistungsgrenzwert Entladen
  initial: "0"
  options:
    - "4600"
    - "2500"
    - "1000"
    - "750"
    - "500"
    - "0"
  icon: mdi:battery-arrow-up
sax_a_leistungsgrenzwert_laden:
  name: Leistungsgrenzwert Laden
  initial: "3500"
  options:
    - "3500"
    - "0"
  icon: mdi:battery-arrow-down-outline
